name: FrameOS
version: main-47bce6a
slug: frameos
image: frameos/frameos
description: Manage smart frames with FrameOS
url: https://github.com/FrameOS/frameos-home-assistant-addon
logo: https://raw.githubusercontent.com/FrameOS/frameos-home-assistant-addon/refs/heads/main/frameos/logo.png
panel_icon: mdi:image-frame
ingress: true
ingress_port: 8990
startup: services
init: false
arch:
  - aarch64
  - amd64
map:
  - type: data
    read_only: false
services: []
environment:
  DATABASE_URL: "sqlite:////data/frameos.db"
ports:
  8989/tcp: 8989
  8990/tcp: null
ports_description:
  8989/tcp: "FrameOS public API port for incoming logs"
  8990/tcp: "FrameOS ingress port, not exposed"
