name: FrameOS
version: latest
slug: frameos
image: mariusandra/frameos-hassio-test
description: Manage smart frames with FrameOS
url: https://github.com/FrameOS/frameos-home-assistant-addon
logo: https://raw.githubusercontent.com/FrameOS/frameos-home-assistant-addon/refs/heads/main/frameos/logo.png
panel_icon: mdi:image-frame
ingress: true
ingress_port: 8990
ingress_entry: /
# ingress_stream: true
startup: services
init: false
arch:
  - aarch64
  - amd64
map:
  - type: data
    read_only: false
services: []
options:
  secret_key: ""
schema:
  secret_key: str?
environment:
  RUNNING_AS_HA_ADDON: "1"
  SECRET_KEY: "$secret_key"
  SQLALCHEMY_DATABASE_URI: "sqlite:////data/frameos.db"
ports:
  8989/tcp: 8989
  8990/tcp: 8990
webui: "http://[HOST]:[PORT:8990]"
