name: FrameOS
version: main-b20e3783179148daaf75445f2d0c8060d0b2184c
slug: frameos
description: Run FrameOS as a Home Assistant add-on
url: https://github.com/FrameOS/frameos-home-assistant-addon
ingress: true
ingress_port: 8989
ingress_stream: true
startup: services
init: false
arch:
- aarch64
- amd64
uart: true
hassio_api: false
homeassistant_api: true
map:
- type: addons
  read_only: false
# - type: all_addon_configs
#   read_only: false
- type: backup
  read_only: false
- type: homeassistant_config
  read_only: false
  path: /config
- type: media
  read_only: false
# - type: share
#   read_only: false
- type: ssl
  read_only: false
services: []
# - mysql:want
# - mqtt:want
options:
  packages: []
  init_commands: []
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  config_path: str?
  packages:
  - str
  init_commands:
  - str
image: frameos/frameos