name: FrameOS
version: "1.0.0"
slug: frameos
description: Run FrameOS as a Home Assistant add-on
arch:
  - aarch64
  - amd64
  - armv7
  - armhf
startup: services
boot: auto
host_network: true
ports:
  8989/tcp: 8989
webui: "http://[HOST]:8989"
options: {}
schema: {}
