name: FrameOS
version: main-bf914f043fa06fd2bffe6f69db9817d3f3a2112f
slug: frameos
image: frameos/frameos
description: Manage smart frames with FrameOS
url: https://github.com/FrameOS/frameos-home-assistant-addon
logo: https://raw.githubusercontent.com/FrameOS/frameos-home-assistant-addon/refs/heads/main/frameos/logo.png
icon: mdi:image-frame
# ingress: true
# ingress_port: 8989
# ingress_stream: true
startup: services
init: false
arch:
- aarch64
- amd64
uart: true
realtime: true
# homeassistant_api: true
host_network: true
map:
- type: data
  read_only: false
services: []
options:
  secret_key: ""
schema:
  secret_key: str?
environment:
  RUNNING_AS_HA_ADDON: "1"
  SECRET_KEY: "$secret_key"
  SQLALCHEMY_DATABASE_URI: "sqlite:////data/frameos.db"
ports:
  8989/tcp: 8989
webui: "http://[HOST]:[PORT:8989]"