name: FrameOS
version: "main-b20e3783179148daaf75445f2d0c8060d0b2184c"
maintainer: FrameOS
slug: frameos
description: Run FrameOS as a Home Assistant add-on
url: https://github.com/FrameOS/frameos-home-assistant-addon
ingress: true
ingress_port: 8989
ingress_stream: true
arch:
  - aarch64
  - amd64
  - armv7
startup: services
boot: auto
homeassistant_api: true
host_network: true
image: "frameos/frameos"
options:
  secret_key: ""
schema:
  secret_key: str
environment:
  - RUNNING_AS_HA_ADDON=1
  - SECRET_KEY=$secret_key
  - DATABASE_PATH=/data/db
map:
  - data:rw
webui: "http://[HOST]:8989"
