name: FrameOS
version: main-77fa1723d93fb71cebc6b18bbaf2aaccc6f328e9
slug: frameos
description: Run FrameOS as a Home Assistant add-on
url: https://github.com/FrameOS/frameos-home-assistant-addon
ingress: true
ingress_port: 8989
ingress_stream: true
startup: services
init: false
arch:
- aarch64
- amd64
uart: true
hassio_api: false
homeassistant_api: true
map:
- type: data
  read_only: false
- type: ssl
  read_only: false
services: []
options:
  packages: []
  init_commands: []
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  config_path: str?
  packages:
  - str
  init_commands:
  - str
image: frameos/frameos


# name: FrameOS
# version: "main-b20e3783179148daaf75445f2d0c8060d0b2184c"
# maintainer: FrameOS
# slug: frameos
# description: Run FrameOS as a Home Assistant add-on
# url: https://github.com/FrameOS/frameos-home-assistant-addon
# ingress: true
# ingress_port: 8989
# ingress_stream: true
# arch:
#   - aarch64
#   - amd64
#   - armv7
# startup: services
# boot: auto
# homeassistant_api: true
# host_network: true
# image: "frameos/frameos"
# options:
#   secret_key: ""
# schema:
#   secret_key: str
# environment:
#   - RUNNING_AS_HA_ADDON=1
#   - SECRET_KEY=$secret_key
#   - DATABASE_PATH=/data/db
# map:
#   - data:rw
# webui: "http://[HOST]:8989"
