name: FrameOS
version: "main-b20e3783179148daaf75445f2d0c8060d0b2184c"
slug: frameos
description: Run FrameOS as a Home Assistant add-on
url: https://github.com/FrameOS/frameos-home-assistant-addon
startup: services
boot: auto
ingress: true
ingress_port: 8989
ingress_stream: true
arch:
  - aarch64
  - amd64
  - armv7
homeassistant_api: true
host_network: true
options: {}
schema: {}
image: frameos/frameos
