version: "main-b20e3783179148daaf75445f2d0c8060d0b2184c"
name: FrameOS
maintainer: FrameOS
slug: frameos
description: Run FrameOS as a Home Assistant add-on
arch:
  - aarch64
  - amd64
  - armv7
startup: services
boot: auto
host_network: true
full_access: false  # Set to true only if necessary
image: "frameos/frameos:main-b20e3783179148daaf75445f2d0c8060d0b2184c"
options:
  secret_key: ""
schema:
  secret_key: str
environment:
  - RUNNING_AS_HA_ADDON=1
  - SECRET_KEY=$secret_key
  - DATABASE_PATH=/data/db
map:
  - data:rw
ports:
  8989/tcp: 8989
webui: "http://[HOST]:8989"
